language: scala
sudo: false
jdk: oraclejdk8
scala: 2.12.4

before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

addons:
  sonarqube:
    organization: flux-coordinator

services:
  - mongodb

before_script:
  - sleep 15
  - mongo flux_test --eval 'db.createUser({user: "flux-db-user", pwd: "FMzy5WT/Bv+e", roles:["readWrite"]});'

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sonar-scanner
  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm